//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Public.Pages.Mission {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MissionDetailResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MissionDetailResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Public.Pages.Mission.MissionDetailResources" +
                            "", typeof(MissionDetailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HubPageTitle {
            get {
                return ResourceManager.GetString("HubPageTitle", resourceCulture);
            }
        }
        
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        internal static string EditMissionButton {
            get {
                return ResourceManager.GetString("EditMissionButton", resourceCulture);
            }
        }
        
        internal static string AllMissionsButton {
            get {
                return ResourceManager.GetString("AllMissionsButton", resourceCulture);
            }
        }
        
        internal static string DownloadModpackButton {
            get {
                return ResourceManager.GetString("DownloadModpackButton", resourceCulture);
            }
        }
        
        internal static string SlottingButton {
            get {
                return ResourceManager.GetString("SlottingButton", resourceCulture);
            }
        }
        
        internal static string EditMissionTooltip {
            get {
                return ResourceManager.GetString("EditMissionTooltip", resourceCulture);
            }
        }
        
        internal static string SlottingButtonTooltip {
            get {
                return ResourceManager.GetString("SlottingButtonTooltip", resourceCulture);
            }
        }
    }
}
