//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginWith2faResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginWith2faResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.LoginWith2faResource" +
                            "", typeof(LoginWith2faResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvoufázové Ověřování.
        /// </summary>
        public static string _2faLogin {
            get {
                return ResourceManager.GetString("2faLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvůj účet je chráněn dvoufázovým ověřováním. Pro přihlášení zadej kód z ověřovací aplikace..
        /// </summary>
        public static string AccountSecuredWith2fa {
            get {
                return ResourceManager.GetString("AccountSecuredWith2fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný ověřovací kód je nesprávný.
        /// </summary>
        public static string Invalid2faCode {
            get {
                return ResourceManager.GetString("Invalid2faCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáš přístup k ověřovací aplikaci? Můžeš se.
        /// </summary>
        public static string No2faCode1 {
            get {
                return ResourceManager.GetString("No2faCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to přihlásit se záložním kódem.
        /// </summary>
        public static string No2faCode2 {
            get {
                return ResourceManager.GetString("No2faCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na tomto zařízení už nepožadovat.
        /// </summary>
        public static string RememberMachine {
            get {
                return ResourceManager.GetString("RememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověřovací kód.
        /// </summary>
        public static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se načíst uživatele.
        /// </summary>
        public static string UnableToLoad2faUser {
            get {
                return ResourceManager.GetString("UnableToLoad2faUser", resourceCulture);
            }
        }
    }
}
