//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        public static string DeletedModpackType {
            get {
                return ResourceManager.GetString("DeletedModpackType", resourceCulture);
            }
        }
        
        public static string DeletedMissionCategory {
            get {
                return ResourceManager.GetString("DeletedMissionCategory", resourceCulture);
            }
        }
        
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        public static string Slotting {
            get {
                return ResourceManager.GetString("Slotting", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string StringLengthRange {
            get {
                return ResourceManager.GetString("StringLengthRange", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }
        
        public static string StringLengthMax {
            get {
                return ResourceManager.GetString("StringLengthMax", resourceCulture);
            }
        }
        
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        public static string VerifyButton {
            get {
                return ResourceManager.GetString("VerifyButton", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string MissionCreator {
            get {
                return ResourceManager.GetString("MissionCreator", resourceCulture);
            }
        }
        
        public static string MissionType {
            get {
                return ResourceManager.GetString("MissionType", resourceCulture);
            }
        }
        
        public static string ModpackType {
            get {
                return ResourceManager.GetString("ModpackType", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        public static string ResetFilterButton {
            get {
                return ResourceManager.GetString("ResetFilterButton", resourceCulture);
            }
        }
        
        public static string MissionDate {
            get {
                return ResourceManager.GetString("MissionDate", resourceCulture);
            }
        }
        
        public static string MissionName {
            get {
                return ResourceManager.GetString("MissionName", resourceCulture);
            }
        }
        
        public static string MissionConnectingToServer {
            get {
                return ResourceManager.GetString("MissionConnectingToServer", resourceCulture);
            }
        }
        
        public static string MissionStartTime {
            get {
                return ResourceManager.GetString("MissionStartTime", resourceCulture);
            }
        }
    }
}
