//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Public.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Public.Pages.IndexResource", typeof(IndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuálně platné zákazy.
        /// </summary>
        internal static string ActivePunishments {
            get {
                return ResourceManager.GetString("ActivePunishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstraněná kategorie.
        /// </summary>
        internal static string DeletedMissionCategory {
            get {
                return ResourceManager.GetString("DeletedMissionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstraněný typ.
        /// </summary>
        internal static string DeletedModpackType {
            get {
                return ResourceManager.GetString("DeletedModpackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstraněný uživatel.
        /// </summary>
        internal static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout Modpack.
        /// </summary>
        internal static string DownloadModpack {
            get {
                return ResourceManager.GetString("DownloadModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string MissionAuthor {
            get {
                return ResourceManager.GetString("MissionAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie Mise.
        /// </summary>
        internal static string MissionCategory {
            get {
                return ResourceManager.GetString("MissionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojování na Server.
        /// </summary>
        internal static string MissionConnecting {
            get {
                return ResourceManager.GetString("MissionConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velitelský Briefing.
        /// </summary>
        internal static string MissionLeaderBriefing {
            get {
                return ResourceManager.GetString("MissionLeaderBriefing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ Modpacku.
        /// </summary>
        internal static string MissionModpack {
            get {
                return ResourceManager.GetString("MissionModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string MissionName {
            get {
                return ResourceManager.GetString("MissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise v příštích 7 dnech.
        /// </summary>
        internal static string MissionsInUpcomingDays {
            get {
                return ResourceManager.GetString("MissionsInUpcomingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek Mise.
        /// </summary>
        internal static string MissionStart {
            get {
                return ResourceManager.GetString("MissionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V tuto chvíli nemá nikdo platný zákaz..
        /// </summary>
        internal static string NoActivePunishments {
            get {
                return ResourceManager.GetString("NoActivePunishments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na misi není upravený modpack. Použij aktivátor..
        /// </summary>
        internal static string NoCustomModpack {
            get {
                return ResourceManager.GetString("NoCustomModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na neurčito.
        /// </summary>
        internal static string NoExpirationDate {
            get {
                return ResourceManager.GetString("NoExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není plánován.
        /// </summary>
        internal static string NoLeaderBriefingPlanned {
            get {
                return ResourceManager.GetString("NoLeaderBriefingPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnes se nekoná žádná mise..
        /// </summary>
        internal static string NoMissionToday {
            get {
                return ResourceManager.GetString("NoMissionToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V následujících dnech nejsou plánovány žádné mise.
        /// </summary>
        internal static string NoUpcomingMissions {
            get {
                return ResourceManager.GetString("NoUpcomingMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuálně nejsou plánovány žádné výcviky..
        /// </summary>
        internal static string NoUpcomingTrainings {
            get {
                return ResourceManager.GetString("NoUpcomingTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken Grenade Hub.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vypršení.
        /// </summary>
        internal static string PunishmentExpiration {
            get {
                return ResourceManager.GetString("PunishmentExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trest.
        /// </summary>
        internal static string PunishmentName {
            get {
                return ResourceManager.GetString("PunishmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        internal static string PunishmentUser {
            get {
                return ResourceManager.GetString("PunishmentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotování.
        /// </summary>
        internal static string Slotting {
            get {
                return ResourceManager.GetString("Slotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotování nebylo autorem dodáno..
        /// </summary>
        internal static string SlottingNotProvided {
            get {
                return ResourceManager.GetString("SlottingNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnešní mise.
        /// </summary>
        internal static string TodaysMission {
            get {
                return ResourceManager.GetString("TodaysMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string UpcomingMissionAuthor {
            get {
                return ResourceManager.GetString("UpcomingMissionAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string UpcomingMissionDate {
            get {
                return ResourceManager.GetString("UpcomingMissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string UpcomingMissionDetail {
            get {
                return ResourceManager.GetString("UpcomingMissionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modpack.
        /// </summary>
        internal static string UpcomingMissionModpack {
            get {
                return ResourceManager.GetString("UpcomingMissionModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string UpcomingMissionName {
            get {
                return ResourceManager.GetString("UpcomingMissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string UpcomingTrainingDate {
            get {
                return ResourceManager.GetString("UpcomingTrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string UpcomingTrainingDetail {
            get {
                return ResourceManager.GetString("UpcomingTrainingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktor.
        /// </summary>
        internal static string UpcomingTrainingInstructor {
            get {
                return ResourceManager.GetString("UpcomingTrainingInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string UpcomingTrainingName {
            get {
                return ResourceManager.GetString("UpcomingTrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadcházející  výcviky.
        /// </summary>
        internal static string UpcomingTrainings {
            get {
                return ResourceManager.GetString("UpcomingTrainings", resourceCulture);
            }
        }
    }
}
