//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Public.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Public.Pages.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HubPageTitle {
            get {
                return ResourceManager.GetString("HubPageTitle", resourceCulture);
            }
        }
        
        public static string TodaysMission {
            get {
                return ResourceManager.GetString("TodaysMission", resourceCulture);
            }
        }
        
        public static string NoMissionToday {
            get {
                return ResourceManager.GetString("NoMissionToday", resourceCulture);
            }
        }
        
        public static string MissionName {
            get {
                return ResourceManager.GetString("MissionName", resourceCulture);
            }
        }
        
        public static string MissionAuthor {
            get {
                return ResourceManager.GetString("MissionAuthor", resourceCulture);
            }
        }
        
        public static string MissionCategory {
            get {
                return ResourceManager.GetString("MissionCategory", resourceCulture);
            }
        }
        
        public static string MissionModpack {
            get {
                return ResourceManager.GetString("MissionModpack", resourceCulture);
            }
        }
        
        public static string MissionLeaderBriefing {
            get {
                return ResourceManager.GetString("MissionLeaderBriefing", resourceCulture);
            }
        }
        
        public static string MissionConnecting {
            get {
                return ResourceManager.GetString("MissionConnecting", resourceCulture);
            }
        }
        
        public static string MissionStart {
            get {
                return ResourceManager.GetString("MissionStart", resourceCulture);
            }
        }
        
        public static string NoLeaderBriefingPlanned {
            get {
                return ResourceManager.GetString("NoLeaderBriefingPlanned", resourceCulture);
            }
        }
        
        public static string NoCustomModpack {
            get {
                return ResourceManager.GetString("NoCustomModpack", resourceCulture);
            }
        }
        
        public static string DownloadModpack {
            get {
                return ResourceManager.GetString("DownloadModpack", resourceCulture);
            }
        }
        
        public static string SlottingNotProvided {
            get {
                return ResourceManager.GetString("SlottingNotProvided", resourceCulture);
            }
        }
        
        public static string MissionsInUpcomingDays {
            get {
                return ResourceManager.GetString("MissionsInUpcomingDays", resourceCulture);
            }
        }
        
        public static string UpcomingMissionName {
            get {
                return ResourceManager.GetString("UpcomingMissionName", resourceCulture);
            }
        }
        
        public static string UpcomingMissionAuthor {
            get {
                return ResourceManager.GetString("UpcomingMissionAuthor", resourceCulture);
            }
        }
        
        public static string UpcomingMissionModpack {
            get {
                return ResourceManager.GetString("UpcomingMissionModpack", resourceCulture);
            }
        }
        
        public static string UpcomingMissionDate {
            get {
                return ResourceManager.GetString("UpcomingMissionDate", resourceCulture);
            }
        }
        
        public static string NoUpcomingMissions {
            get {
                return ResourceManager.GetString("NoUpcomingMissions", resourceCulture);
            }
        }
        
        public static string UpcomingTrainings {
            get {
                return ResourceManager.GetString("UpcomingTrainings", resourceCulture);
            }
        }
        
        public static string UpcomingTrainingDate {
            get {
                return ResourceManager.GetString("UpcomingTrainingDate", resourceCulture);
            }
        }
        
        public static string UpcomingTrainingName {
            get {
                return ResourceManager.GetString("UpcomingTrainingName", resourceCulture);
            }
        }
        
        public static string UpcomingTrainingInstructor {
            get {
                return ResourceManager.GetString("UpcomingTrainingInstructor", resourceCulture);
            }
        }
        
        public static string NoUpcomingTrainings {
            get {
                return ResourceManager.GetString("NoUpcomingTrainings", resourceCulture);
            }
        }
        
        public static string UpcomingTrainingDetail {
            get {
                return ResourceManager.GetString("UpcomingTrainingDetail", resourceCulture);
            }
        }
        
        public static string UpcomingMissionDetail {
            get {
                return ResourceManager.GetString("UpcomingMissionDetail", resourceCulture);
            }
        }
        
        public static string ActivePunishments {
            get {
                return ResourceManager.GetString("ActivePunishments", resourceCulture);
            }
        }
        
        public static string PunishmentUser {
            get {
                return ResourceManager.GetString("PunishmentUser", resourceCulture);
            }
        }
        
        public static string PunishmentExpiration {
            get {
                return ResourceManager.GetString("PunishmentExpiration", resourceCulture);
            }
        }
        
        public static string PunishmentName {
            get {
                return ResourceManager.GetString("PunishmentName", resourceCulture);
            }
        }
        
        public static string NoActivePunishments {
            get {
                return ResourceManager.GetString("NoActivePunishments", resourceCulture);
            }
        }
        
        public static string NoExpirationDate {
            get {
                return ResourceManager.GetString("NoExpirationDate", resourceCulture);
            }
        }
    }
}
