//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Disable2faResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Disable2faResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage.Disable2faRes" +
                            "ource", typeof(Disable2faResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samotná deaktivace nezmění klíče používané ověřovací aplikací. Pokud si je přeješ změnit, můžeš to udělat &lt;a asp-page=&quot;{0}&quot;&gt;zde&lt;/a&gt;..
        /// </summary>
        public static string Disable2faAlertMessage {
            get {
                return ResourceManager.GetString("Disable2faAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato akce pouze deaktivuje dvoufázové ověřování.
        /// </summary>
        public static string Disable2faAlertTitle {
            get {
                return ResourceManager.GetString("Disable2faAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovat dvoufázové ověřování.
        /// </summary>
        public static string Disable2faButton {
            get {
                return ResourceManager.GetString("Disable2faButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivace dvoufázového ověřování.
        /// </summary>
        public static string Disable2faTitle {
            get {
                return ResourceManager.GetString("Disable2faTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvoufázové ověřování bylo deaktivováno. Opětovnou aktivaci můžeš provést nastavením ověřovací aplikace..
        /// </summary>
        public static string Disabled2faConfirmation {
            get {
                return ResourceManager.GetString("Disabled2faConfirmation", resourceCulture);
            }
        }
    }
}
