//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnableAuthenticatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnableAuthenticatorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage.EnableAuthent" +
                            "icatorResource", typeof(EnableAuthenticatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do telefonu si stáhni ověřovací aplikaci jako například Google Authenticator pro.
        /// </summary>
        public static string DownloadInstruction1 {
            get {
                return ResourceManager.GetString("DownloadInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nebo Microsoft Authenticator pro.
        /// </summary>
        public static string DownloadInstruction2 {
            get {
                return ResourceManager.GetString("DownloadInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poté, co jsi nasketoval QR kód (nebo opsal klíč), ti ověřovací aplikace vygeneruje kód. Opiš daný kód do políčka níže..
        /// </summary>
        public static string Enable2faCodeInstructions {
            get {
                return ResourceManager.GetString("Enable2faCodeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace byla úspěšně ověřena dvoufázová verifikace aktivována..
        /// </summary>
        public static string Enable2faConfirmation {
            get {
                return ResourceManager.GetString("Enable2faConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro nastavení ověřovací aplikace následuj tyto kroky:.
        /// </summary>
        public static string Enable2faIntroductionInstructions {
            get {
                return ResourceManager.GetString("Enable2faIntroductionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V aplikaci naskenuj QR kód zobrazený níže nebo opiš následující klíč:.
        /// </summary>
        public static string Enable2faScanInstructions {
            get {
                return ResourceManager.GetString("Enable2faScanInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení ověřovací aplikace.
        /// </summary>
        public static string Enable2faTitle {
            get {
                return ResourceManager.GetString("Enable2faTitle", resourceCulture);
            }
        }
    }
}
