//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenerateRecoveryCodesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenerateRecoveryCodesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Identity.Pages.Account.Manage.GenerateRecov" +
                            "eryCodesResource", typeof(GenerateRecoveryCodesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generování záložních kódů.
        /// </summary>
        public static string GenerateRecoveryCodesTitle {
            get {
                return ResourceManager.GetString("GenerateRecoveryCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vygenerovat záložní klíče.
        /// </summary>
        public static string GenerateRecoveryKeysButton {
            get {
                return ResourceManager.GetString("GenerateRecoveryKeysButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vygenerování nových záložních klíčů neovlivní funkčnost aktuálně používané ověřovací aplikace. Pokud ji chceš obnovit, měl by jsi &lt;a asp-page=&quot;{0}&quot;&gt;obnovit ověřovací aplikaci&lt;/a&gt;..
        /// </summary>
        public static string GeneratingNewCodes {
            get {
                return ResourceManager.GetString("GeneratingNewCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud ztratíš telefon s ověřovací aplikací a nebueš mít tyto záložní kódy, ztratíš přístup ke svému účtu..
        /// </summary>
        public static string NoCodesNoAccount {
            get {
                return ResourceManager.GetString("NoCodesNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové záložní kódy byly úspěšně vygenerovány.
        /// </summary>
        public static string RecoveryCodesGeneratedConfirmation {
            get {
                return ResourceManager.GetString("RecoveryCodesGeneratedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulož si tyto kódy na bezpečném místě..
        /// </summary>
        public static string SaveCodesInSafePlace {
            get {
                return ResourceManager.GetString("SaveCodesInSafePlace", resourceCulture);
            }
        }
    }
}
