//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokenGrenade.Web.App.Resources.Areas.Public.Pages.Training {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrainingListResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrainingListResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BrokenGrenade.Web.App.Resources.Areas.Public.Pages.Training.TrainingListResources" +
                            "", typeof(TrainingListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HubPageTitle {
            get {
                return ResourceManager.GetString("HubPageTitle", resourceCulture);
            }
        }
        
        internal static string NameFilter {
            get {
                return ResourceManager.GetString("NameFilter", resourceCulture);
            }
        }
        
        internal static string CreatorFilter {
            get {
                return ResourceManager.GetString("CreatorFilter", resourceCulture);
            }
        }
        
        internal static string DateFilter {
            get {
                return ResourceManager.GetString("DateFilter", resourceCulture);
            }
        }
        
        internal static string NoTrainingsFound {
            get {
                return ResourceManager.GetString("NoTrainingsFound", resourceCulture);
            }
        }
    }
}
